[package]
name = "wasm-react"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
wasm-bindgen = "0.2.80"
js-sys = "0.3.57"

[dependencies.web-sys]
version = "0.3.57"
features = [
  "Event", "MouseEvent", "FocusEvent", "KeyboardEvent", "DragEvent",
  "PointerEvent", "WheelEvent", "AnimationEvent", "TransitionEvent"
]
